# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9bfea150e35b3691590b2f82eeec2cb28b9b225123d0af44cee2ef6c7f9e59185fe5a959b99b3747cbdbd5ca35ea1ce8d7dc96ad719edac22141d57325ae3f1

test:
  secret_key_base: 99d18ede1e333b9eecc42ea254b1026e3f193c852c5ac0e82031a434bed98a47a1502fec141ce880007d37862da2b58c57a789b2268df96fa4c043b460812500

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
